server:
  port: 9090

spring:
  application:
    name: online-study-server
  profiles:
    active: dev
  datasource:
    driver-class-name: ${online-study.datasource.driver-class-name}
    name: online_study
    url: jdbc:mysql://${online-study.datasource.host}:${online-study.datasource.port}/${online-study.datasource.database}
    username: ${online-study.datasource.username}
    password: ${online-study.datasource.password}
  data:
    redis:
      host: ${online-study.redis.host}
      port: ${online-study.redis.port}
      password: ${online-study.redis.password}
      database: ${online-study.redis.database}
  mail:
    host: smtp.163.com
    port: 465
    username: Online_Study@163.com
    password: EUaFz37FV4XjrXxN
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      study:
        mapper: debug
        service: info
        controller: info

online-study:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: AdminStudySamGoldSeeHuangchunxinLZFMJLXYX
    client-secret-key: ClientStudySamGoldSeeHuangchunxinLZFMJLXYX
    # 设置jwt过期时间，单位毫秒
    admin-ttl: 7200000
    client-ttl: 7200000
    # 设置前端传递过来的令牌名称，键
    admin-token-name: token
    client-token-name: authentication