server:
  port: 8080

spring:
  application:
    name: online-study-server
  profiles:
    active: dev
  datasource:
    driver-class-name: ${online-study.datasource.driver-class-name}
    name: test
    url: jdbc:mysql://${online-study.datasource.host}:${online-study.datasource.port}/${online-study.datasource.database}
    username: ${online-study.datasource.username}
    password: ${online-study.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      study:
        mapper: debug
        service: info
        controller: info