spring:
  application:
    name: online-study-server
  datasource:
    druid:
      driver-class-name: ${online-study.datasource.driver-class-name}
      url: jdbc:mysql://${online-study.datasource.host}:${online-study.datasource.port}/${online-study.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${online-study.datasource.username}
      password: ${online-study.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true